@echo off
echo Copyright. Banne and Co. Do Copy this dongly hangly shit.

title BanHammer. Bye banne and co.
echo The BanHammer.
echo --------------------------------
echo Version: 1.1
echo Update Notes: WORKS!!!!
echo --------------------------------
echo Starting BanHammer by banne and co.
echo _______________BANHAMEMR
echo The banhammer is activating!
echo Activing!
echo Done
pause
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The shit hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
echo Bestrow The hammer!
pause
echo Entering Cooldown mode!!
pause
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo BanHammer has deactivated.
echo Any Key will drop the Hammer
pause
echo fuck my pussssssy!